Added --skip-validation option
ckeditor/ckbuilder pull request #33
Opened 2021-01-15 12:35 UTC by vokiel

Closes #32

2021-01-15 17:03 UTC, f1ames requested changes
If I add spreadsheet plugin to build config like:

```
spreadsheet: 1
```

and run build with:

```sh
./build.sh standard --skip-validation 2
```

The validation error is still there :thinking: 

![image](https://user-images.githubusercontent.com/1061942/104755603-f1c7ac00-575a-11eb-9164-f92902bc6a59.png)

Same with (without spreadsheet in config):

```sh
./build.sh standard all --skip-validation 2
```

And with:

```sh
./build.sh standard --skip-validation 2 -r spreadsheet
```

Tried also with `--skip-validation=2` but the result is the same :thinking: And it seems the `jar` is fine since the options is recognized correctly (no error about unrecognized option).

@vokiel any ideas? :thinking:

2021-01-15 17:04 UTC, f1ames commented on src/lib/controller.js
> +		[ null, "skip-validation", [ "LEVEL", "skip validation level (0, 1, 2)." ], "sets the skip validation level" ],
Ok, now I see level 1 checks for non-existing plugin files only but doesn't validate JS.

2021-01-15 17:05 UTC, f1ames commented on src/lib/controller.js
> +		[ null, "skip-validation", [ "LEVEL", "skip validation level (0, 1, 2)." ], "sets the skip validation level" ],
While `0` does both checks and `2` skips both checks.

2021-01-16 09:36 UTC, f1ames commented
I had an aha moment suddenly and realized that I was passing `--skip-validation` flag to `build.sh` script instead of `ckbuilder.jar` directly... so called "Friday evening effect"... :sweat\_smile::facepalm::see\_no\_evil: 

So ignore my previous [https://github.com/ckeditor/ckbuilder/pull/33#pullrequestreview-569412882](https://github.com/ckeditor/ckbuilder/pull/33#pullrequestreview-569412882) comment as I need to take another look on this PR :crossed\_fingers:

2021-01-18 08:17 UTC, vokiel commented
We use it like this:

```shell
java -jar ckbuilder.jar --no-ie-checks --preprocess-plugin --leave-js-unminified --skip-validation=1 --overwrite /path_to_plugin
```

2021-01-18 09:04 UTC, f1ames reviewed
Thanks @vokiel for the [https://github.com/ckeditor/ckbuilder/pull/33#issuecomment-762070370](https://github.com/ckeditor/ckbuilder/pull/33#issuecomment-762070370) - I was able to figure out how to use it :+1: 

Using it as you mentioned works as expected. So I was able to use:

```shell
java -jar ckbuilder.jar --no-ie-checks --preprocess-plugin --leave-js-unminified --skip-validation=0\1\2 --overwrite /path_to_plugin
```

and it worked as expected.

What made me confused was the fact that it works only with `--preprocess-plugin` (that's my assumption) because running it with the way presets use `ckbuilder.jar`:

```
java -jar ckbuilder/2.4.2/ckbuilder.jar --build ckeditor build/4.15.2/standard -s  --version="4.15.2 (Standard)" --revision ece98ca43 --build-config presets/standard-build-config.js --skip-validation=0/1/2 --no-zip --no-tar --overwrite  standard
```

always failed due to validation. So it means **this flag can be only used when pre-processing single plugin and not building entire editor. Is it correct @vokiel?** :thinking: 

This is basically how we use it and what we need so I'm fine with it. It will be good to mention in the option description (I can take care of that).

2021-01-18 14:39 UTC, f1ames approved these changes
LGTM :+1: :clap: 

We have adjusted option name and its description to be more meaningful.

2021-01-18 14:42 UTC, merged