Update license: year & company name
ckeditor/ckbuilder pull request #35
Opened 2022-02-01 10:17 UTC by sculpt0r

Changes made with https://github.com/ckeditor/ckeditor4/blob/master/dev/license/updatelicense.js with a few manual corrections.

2022-02-01 10:46 UTC, vokiel requested changes
To update:
- Trailing slashes.
- HTTP => HTTPS

2022-02-01 10:46 UTC, vokiel commented on src/lib/utils.js
> +				copyright = "/*" + eol + "Copyright (c) 2003-" + date.getFullYear() + ", CKSource Holding sp. z o.o. All rights reserved." + eol + "For licensing, see LICENSE.md or https://ckeditor.com/legal/cke
Please add trailing slash to the URL:

```suggestion
				copyright = "/*" + eol + "Copyright (c) 2003-" + date.getFullYear() + ", CKSource Holding sp. z o.o. All rights reserved." + eol + "For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license/" + eol + "*/" + eol;
```

Also along with any other places when it occurs.

2022-02-01 10:46 UTC, vokiel commented on test/_assets/samples/ckeditor-dev-correct/samples/old/api.html
> +			Copyright &copy; 2003-2022, <a class="samples" href="http://cksource.com/">CKSource</a> Holding sp. z o.o. All rights reserved.
Use HTTPS (fix in all samples):

```suggestion
			Copyright &copy; 2003-2022, <a class="samples" href="https://cksource.com/">CKSource</a> Holding sp. z o.o. All rights reserved.
```

2022-02-01 10:46 UTC, vokiel commented on test/_assets/samples/ckeditor-dev-correct/samples/old/api.html
>  			CKEditor - The text editor for the Internet - <a class="samples" href="http://ckeditor.com/">http://ckeditor.com</a>
Use HTTPS (fix in all samples):

```suggestion
			CKEditor - The text editor for the Internet - <a class="samples" href="https://ckeditor.com/">https://ckeditor.com/</a>
```

2022-02-01 10:46 UTC, vokiel commented on docs/jsduck.json
> +	"--footer": "Copyright &copy; 2012-2014, <a href=\"http://cksource.com\" style=\"color:#085585\">CKSource</a> Holding sp. z o.o. All rights reserved. | Generated with <a href=\"https://github.com/se
Use HTTPS

```suggestion
	"--footer": "Copyright &copy; 2012-2014, <a href=\"https://cksource.com/\" style=\"color:#085585\">CKSource</a> Holding sp. z o.o. All rights reserved. | Generated with <a href=\"https://github.com/senchalabs/jsduck\">JSDuck</a>.",
```

2022-02-01 11:35 UTC, sculpt0r commented
@vokiel ready for another review
- added trailing slashes to the license URLs
- used `https` for all URLs
- also, I found a few more places that require updating the year and company name - so there are also updated

2022-02-01 11:45 UTC, vokiel commented
@sculpt0r  you showed another places we could fix ;-)

Links to addons repo should have `cke4` inside, the same with the CKE4 builder:

`https://ckeditor.com/addons/skins/all` => `https://ckeditor.com/cke4/addons/skins/all`
`https://ckeditor.com/addon/widget` => `https://ckeditor.com/cke4/addon/widget`
`https://ckeditor.com/builder` => `https://ckeditor.com/cke4/builder`

2022-02-02 05:51 UTC, sculpt0r commented
@vokiel - ready for another review
- `cke4` inserted

Nice that we can correct little something :)

2022-02-02 10:28 UTC, vokiel requested changes
This might take too much time, because after every change I spot some new link that should be changed...

I would skip rest of them besides links to our docs, e.g:
`https://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.dialog.definition` which points to nowhere (old CKSource domain, docs subdomain) => `https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definition.html`

There are also newer links to docs (in ckeditor.com domain):
`https://docs.ckeditor.com/#!/api/CKEDITOR.dialog.definition` that are redirected correctly to `https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definition.html` but we could change them so no redirect will happen.

2022-02-02 11:56 UTC, sculpt0r commented
@vokiel - ready for another review
- added missed trailing slashes (for license URLs and ckeditor.com)
- replace old docs URLs with the newest one
- replaced URLs causing redirection with the newest one
- replaced old ckeditor nightly  URLs with the newest one

You're right - there are still more things coming 😅

2022-02-02 12:02 UTC, vokiel approved these changes

2022-02-02 12:13 UTC, sculpt0r commented
@vokiel  - not sure how do you proceed with merging?  The creator or reviewer of the PR should merge? In CKE4 the reviewer is merging accepted PR 🤔

2022-02-02 12:36 UTC, vokiel commented
We also need someone to create new release. Then deploy new version on our download page, and use it in online builder.

Who's gonna do the build/release?

2022-02-02 12:48 UTC, sculpt0r commented
@jacekbogdanski is doing releases for CKE4. But I have no idea how things are with builder...

2022-02-02 14:58 UTC, vokiel commented
I managed to build CKBuilder locally and tested if those changes are applied. All seems to be working :ok\_hand: So tomorrow I'll merge the branch and create the `2.4.3` release.

2022-02-02 15:12 UTC, jacekbogdanski commented
Thanks guys! We've already discussed with @vokiel that he will handle the whole releasing part. We will have to just bump ckbuilder in https://github.com/ckeditor/ckeditor4-presets/blob/master/build.sh#L48 after that.

2022-02-03 07:35 UTC, merged