Extended CKBuilder to support ESM license header
ckeditor/ckbuilder pull request #37
Opened 2023-07-27 14:25 UTC by jacekbogdanski

I've added an additional option to support LTS license headers.

2023-07-27 14:27 UTC, jacekbogdanski commented on src/lib/tools.js
> +			// `lineEndings` array includes all filetypes supported by CKEditor 4.
It seems like this method is only called for files that had updated line endings, for example language files. I'm not sure if that's the design decision or some oversight - but the binaries of CKEditor 4 should have properly updated license headers for LTS, so I didn't change the original behavior of this script (I've only added support for LTS).

2023-07-28 10:19 UTC, vokiel requested changes
It would be great to have this option also descirbed in the help, e.g. https://github.com/ckeditor/ckbuilder/blob/4ff7ff6f2cac8908d7b1c16f84ec04ada7661553/src/assets/help.txt#L27

2023-07-28 12:54 UTC, jacekbogdanski commented
@vokiel thanks, added 👍🏻

2023-08-08 16:23 UTC, vokiel commented
Tested, it works. Adds proper license header to bilt `ckeditor.js` and to translation files.

But only to them. Other files with copyright header still contains the default:

```javascript
/**
 * @license Copyright (c) 2003-2023, CKSource Holding sp. z o.o. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */
```

2023-08-22 13:13 UTC, merged